import Head from "next/head";
import { Inter } from "next/font/google";
import InputForm from "@/components/InputForm";
import ResponseDisplay from "@/components/ResponseDisplay";
import SubmitButton from "@/components/SubmitButton";
import useApi from "@/hooks/useApi";
import { getUserPrompt } from "../prompts/promptUtils";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, error, loading, fetchData } = useApi();

  const handleSubmit = async (guests, location, description) => {
    const submitValue = getUserPrompt(guests, location, description);
    await fetchData("/api/openai", "POST", submitValue);
  };

  return (
    <>
      <Head>
        <title>AIEventPlanner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1 className={inter.className}>Welcome to the AI-Enhanced Event Planning App</h1>
        <p className={inter.className}>
          Plan your events effortlessly with AI assistance
        </p>
        <InputForm onSubmit={handleSubmit} />
        <SubmitButton onClick={() => handleSubmit()}/>
        <ResponseDisplay data={data} error={error} loading={loading} />
      </main>
    </>
  );
}
